# Generated by Django 4.2.7 on 2023-12-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisewallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='label',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='value',
            new_name='price',
        ),
    ]
