# Generated by Django 4.2.7 on 2023-12-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisewallet', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
