# Generated by Django 4.2.7 on 2023-12-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisewallet', '0007_alter_expense_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
